#!/usr/bin/env python3
"""Evaluate domain generalization to unseen acquisition factors.

This uses the corrected synthetic HDF5 only. ERM is trained on all vendors for
the source levels of one acquisition factor and evaluated on a held-out level.
The source validation split, target scaling, and model configuration match the
authoritative benchmark; target labels are never used for training or selection.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
import sys
sys.path.insert(0, str(ROOT))

from scripts.run_corrected_benchmark import (
    EPOCHS,
    SEEDS,
    evaluate,
    load_data,
    train_model,
)

OUTPUT = ROOT / "results/corrected_factor_holdout.json"
TABLE = ROOT / "paper/generated_factor_holdout_table.tex"


def split_source(indices: np.ndarray, seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    shuffled = indices[rng.permutation(len(indices))]
    n_train = max(1, int(0.8 * len(shuffled)))
    return shuffled[:n_train], shuffled[n_train:]


def run_condition(
    data: dict[str, np.ndarray],
    name: str,
    factor: str,
    source_values: list[float | int],
    target_value: float | int,
    seed: int,
) -> dict:
    values = data["metadata"][factor]
    source_mask = np.isin(values, np.asarray(source_values))
    target_mask = values == target_value
    source_indices = np.flatnonzero(source_mask)
    target_indices = np.flatnonzero(target_mask)
    train_idx, val_idx = split_source(source_indices, seed)
    train_ids = set(data["sample_ids"][train_idx].tolist())
    val_ids = set(data["sample_ids"][val_idx].tolist())
    target_ids = set(data["sample_ids"][target_indices].tolist())
    fold = {
        "target_vendor": name,
        "source_vendors": ["source_factor_levels"],
        "train_idx": train_idx,
        "val_idx": val_idx,
        "target_idx": target_indices,
        "train_domain_counts": {"source_factor_levels": int(len(train_idx))},
        "split_overlap": int(
            len(train_ids & val_ids)
            + len(train_ids & target_ids)
            + len(val_ids & target_ids)
        ),
        "sample_id_overlap": int(
            len(train_ids & val_ids)
            + len(train_ids & target_ids)
            + len(val_ids & target_ids)
        ),
    }
    records = []
    for model_seed in SEEDS:
        domains = np.zeros(len(train_idx), dtype=np.int64)
        _, trained = train_model(
            data,
            fold,
            "erm",
            model_seed,
            train_indices=train_idx,
            train_domains=domains,
        )
        record = trained["result"]
        records.append(
            {
                "seed": int(model_seed),
                "source": record["source"],
                "target": record["target"],
                "ds3": record["ds3"],
                "train_size": record["train_size"],
                "validation_size": int(len(val_idx)),
                "target_size": int(len(target_indices)),
                "target_labels_used_for_training": False,
                "target_scaler_fit_on_source_only": True,
            }
        )
    def summary(path: tuple[str, ...]) -> dict[str, float | int]:
        vals = []
        for row in records:
            value = row
            for key in path:
                value = value[key]
            vals.append(float(value))
        arr = np.asarray(vals, dtype=np.float64)
        return {
            "mean": float(arr.mean()),
            "sd": float(arr.std(ddof=1) if len(arr) > 1 else 0.0),
            "n": int(len(arr)),
        }
    return {
        "name": name,
        "factor": factor,
        "source_values": source_values,
        "target_value": target_value,
        "n_source": int(len(source_indices)),
        "n_target": int(len(target_indices)),
        "n_train": int(len(train_idx)),
        "n_validation": int(len(val_idx)),
        "split_overlap": fold["split_overlap"],
        "sample_id_overlap": fold["sample_id_overlap"],
        "records": records,
        "summary": {
            "source_mae": summary(("source", "mae")),
            "target_mae": summary(("target", "mae")),
            "target_mae_t1": summary(("target", "mae_t1")),
            "target_mae_t2": summary(("target", "mae_t2")),
            "ds3": summary(("ds3",)),
        },
    }


def write_table(results: list[dict]) -> None:
    lines = [
        "% Generated by scripts/run_factor_holdout.py.",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Held-out factor & Source levels & Target level & Source MAE & Target MAE & DS3 \\\\",
        "\\midrule",
    ]
    for result in results:
        s = result["summary"]
        source = f"{s['source_mae']['mean']:.1f} $\\pm$ {s['source_mae']['sd']:.1f}"
        target = f"{s['target_mae']['mean']:.1f} $\\pm$ {s['target_mae']['sd']:.1f}"
        ds3 = f"{s['ds3']['mean']:.2f} $\\pm$ {s['ds3']['sd']:.2f}"
        source_levels = ",".join(str(x) for x in result["source_values"])
        label = result["name"].replace("_", r"\_")
        lines.append(
            f"{label} & {source_levels} & {result['target_value']} & "
            f"{source} & {target} & {ds3} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", "}"])
    TABLE.write_text("\n".join(lines) + "\n")


def main() -> None:
    data = load_data(ROOT / os.environ.get(
        "MRF_DATA", "data/synthetic/mrf_corrected_100k.h5"
    ))
    conditions = [
        {
            "name": "Field strength (3.0 T)",
            "factor": "field_strength",
            "source_values": [1.5],
            "target_value": 3.0,
        },
        {
            "name": "Flip-angle schedule (variant 2)",
            "factor": "fa_variant",
            "source_values": [0, 1],
            "target_value": 2,
        },
        {
            "name": "TR schedule (variant 1)",
            "factor": "tr_variant",
            "source_values": [0],
            "target_value": 1,
        },
    ]
    results = []
    for index, condition in enumerate(conditions):
        print(f"Running {condition['name']} with {EPOCHS} epochs", flush=True)
        results.append(
            run_condition(
                data,
                seed=202600 + index,
                **condition,
            )
        )
    output = {
        "schema_version": "corrected-factor-holdout-v1",
        "protocol": {
            "model": "same ResNet1D-18 configuration as corrected benchmark",
            "algorithm": "ERM",
            "seeds": SEEDS,
            "epochs": EPOCHS,
            "source_split": "80/20 by deterministic sample-ID permutation",
            "target_scaler": "source training only",
            "target_labels_used_for_training": False,
            "target_labels_used_for_model_selection": False,
            "primary_metric": "absolute MAE in ms",
        },
        "conditions": results,
    }
    OUTPUT.write_text(json.dumps(output, indent=2) + "\n")
    write_table(results)
    print(f"Saved {OUTPUT}", flush=True)


if __name__ == "__main__":
    main()
